### ISSUE TITLE
Error when using double colon in selector

### ISSUE THREAD

**Issue by backflip** [css/gonzales#11]
The parser fails on the first occurrence of a double colon in https://github.com/necolas/normalize.css/ (using version 1.3.11 of https://github.com/css/csso):

``` css
button::-moz-focus-inner,
input::-moz-focus-inner {
  border: 0;
  padding: 0;
}
```
